version: "3"

services:
  rabbitmq3:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  app-container:
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq3
    depends_on:
      - rabbitmq3
