version: '3.7'
services:
  demo-app:
    image: claretyoung/spring-rabbitmq-demo:latest
    build: .
    ports:
      - 8080:8080
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    ports:
      - 5672:5672
      - 15672:15672
